### ISSUE TITLE
Template Doesn't Work With Latest Version of Handlebars (2.0)

### ISSUE THREAD

**Issue by prionkor** [k3nsei/ember-twbs-pagination#1]
Script doesn't work with handlebars 2.0. It fails with the error `Unknown template object: function`.

Tested with your given jsbin example just changed url to handlebars and emberjs.

**Comment by prionkor** [comment]
Or the other hand it would be helpful if you can provide the handlebars template. So, we can either add them on the app file or precompile ourself.

**Comment by k3nsei** [comment]
https://github.com/k3nsei/ember-twbs-pagination/blob/master/src/template.hbs
